local neotest = require("neotest")
vim.keymap.set("n", "<leader>tn", function() neotest.run.run() end)
vim.keymap.set("n", "<leader>tf", function() neotest.run.run(vim.fn.expand("%")) end)
vim.keymap.set("n", "<leader>to", function() neotest.output.open({ last_run = true, enter = true }) end)
vim.keymap.set("n", "<leader>tt", function()
    neotest.summary.toggle()
end)
